### ISSUE TITLE
Add namespace service to catalog broker capabilities

### ISSUE THREAD

**Issue by spiegela** [emccode/ecs-cf-service-broker#42]
ECS has the capability to create a new namespace where an application owner can create/delete his/her own buckets for fun & [company] profit.  The ECS broker, rather than creating only buckets, can also support the creation of namespaces.  This would be pretty cool.

The service for a namespace would be configured in the catalog, just like bucket services/plans are now, with many similar options.  configuration for this might looks something like:

```yaml
catalog:
  services:
    - id: f3cbab6a-5172-4ff1-a5c7-72990f0ce2ab
      name: ecs-namespace
      description: Elastic Cloud Namespace
      bindable: true
      planUpdatable: true
      tags:
        - namespace
        - object
      metadata:
        displayName: ecs-namespace
        imageUrl: http://www.emc.com/images/products/header-image-icon-ecs.png
        longDescription: EMC Elastic Cloud Storage (ECS) namespace for creating object storage buckets and CAS pools.
        providerDisplayName: EMC Corporation
        documentationUrl: https://community.emc.com/docs/DOC-45012
        supportUrl: http://www.emc.com/products-solutions/trial-software-download/ecs.htm
      plans:
        - id: 8e777d49-0a78-4cf4-810a-b5f5173b019e
          name: limited
          free: true
          description: Free Trial
          quota-limit: 20
          quota-warning: 18
          bucket-limit: 5
          expiration: {days: 30}
          metadata:
            costs:
              - amount:
                  usd: 0.0
                unit: MONTHLY
            bullets:
              - Shared object storage
              - 20 GB Storage
              - Ability to create up to 5 buckets
```
