### ISSUE TITLE
Add retention period support to catalog and/or service instance parameters

### ISSUE THREAD

**Issue by spiegela** [emccode/ecs-cf-service-broker#44]
Default retention of objects within a bucket can be updated on the bucket at service-instance creation/update.  Support for this might look like:

```shellsession
$ cf create-service ecs-bucket 5gb temp-bucket -c "{ retention: {days: 30} }"
```

This could also be supported in the catalog configuration for a service.  We could add something along the lines of:

```yaml
catalog:
  services:
    - id: <Service ID UUID>
      name: ecs-bucket
      description: Elastic Cloud S3 Object Storage Bucket
      service-settings:
        service-type: bucket
        retention:
          days: 30
```

In the case of YAML catalog configuration, _I think_ the expiration should be come *locked* by the service, meaning that it would override a setting attempted during the service-instance creation.

Need to get some more clarification on this aspect...
