### ISSUE TITLE
Support encryption of buckets

### ISSUE THREAD

**Issue by spiegela** [emccode/ecs-cf-service-broker#45]
The ECS management API now supports a `is_encryption_enabled` tag in the bucket creation.  Need to update the management-client, and the broker options to support this.  Support for this might look something like:

```shellsession
$ cf create-service ecs-bucket 5gb temp-bucket -c "{ encrypt: true }"
```

This could also be supported in the catalog configuration for a service.  We could add something along the lines of:

```yaml
catalog:
  services:
    - id: <Service ID UUID>
      name: ecs-bucket
      description: Elastic Cloud S3 Object Storage Bucket
      service-settings:
        service-type: bucket
        encrypt: true
```

In the case of YAML catalog configuration, _I think_ the expiration should be come *locked* by the service, meaning that it would override a setting attempted during the service-instance creation.

Need to get some more clarification on this aspect...
