### ISSUE TITLE
Problem with catalog bean...?

### ISSUE THREAD

**Issue by camattin** [emccode/ecs-cf-service-broker#69]
I'm receiving "Error creating bean with name 'catalog' defined in class path resource" errors when trying to push the broker service app. Feels like I'm missing something obvious...

My application.yml, manifest.yml and logs from the app startup are all attached.

[application.txt](https://github.com/emccode/ecs-cf-service-broker/files/565296/application.txt)
[manifest.txt](https://github.com/emccode/ecs-cf-service-broker/files/565297/manifest.txt)
[broker-startup.txt](https://github.com/emccode/ecs-cf-service-broker/files/565299/broker-startup.txt)

**Comment by spiegela** [comment]
@camattin From the startup logs, I can see that the _services_ array expected in the Catalog config is `null`.  Perhaps this is because Spring configuration is starting with a different active profile than the `production` profile you've configured in the `application.yml`.

You can try adding the Spring active profile environment variable to your CF `manifest.yml` like so:

```yaml
---
applications:
- name: ecs-broker
  path: ./build/libs/ecs-cf-service-broker-0.0.1-SNAPSHOT.jar
  env:
    SPRING_PROFILES_ACTIVE: production
```
Let me know if that works.

Thanks!

-Aaron
